# Generated by Django 5.1.3 on 2024-11-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('brand_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('entity', models.CharField(max_length=255)),
                ('supplier', models.CharField(max_length=255)),
                ('supplier_id', models.IntegerField()),
                ('supplier_rating', models.FloatField()),
                ('price_u', models.IntegerField()),
                ('sale_price_u', models.IntegerField()),
                ('sale', models.IntegerField()),
                ('rating', models.FloatField()),
                ('review_rating', models.FloatField()),
                ('feedbacks', models.IntegerField()),
                ('total_quantity', models.IntegerField()),
            ],
        ),
    ]
